import React from 'react';
import { Inter } from 'next/font/google';
import StyledComponentsRegistry from '../../lib/AntdRegistry';
import './globals.css'
import Header from '../components/header/page';
import Footer from '../components/footer/page';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en">
    <body className={inter.className}>
      <StyledComponentsRegistry>
        <Header />
        {children}
        <Footer />
      </StyledComponentsRegistry>
    </body>
  </html>
);

export default RootLayout;